name = "Subzero"
uuid = "21f28ab0-737f-4f26-8d5f-51b5b12fb6de"
authors = ["Skylar Gering"]
version = "0.1.0"

[deps]
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
